export const PRODUCT_VERSION = '0.6.100.1';
export const PACKAGE_VERSION = '0.6.100';

export const VERSION = Object.freeze({
    product: PRODUCT_VERSION,
    package: PACKAGE_VERSION,
    accountSave: 4,
    gameState: 5,
    data: 19,
    benchmark: 1,
    codename: 'Continuous Character',
    compatibility: 'migrate-supported-save-versions',
    released: false,

    // Transitional aliases for callers that still use the historical names.
    app: PRODUCT_VERSION,
    save: 5,
});

export const SYSTEM_VERSIONS = Object.freeze({
    versionManifest: '0.6.100.1',
    saveMigrations: '0.3.0',
    actionResults: '0.1.0',
    semanticEvents: '0.1.0',
    foundationReadiness: '0.2.0',
    worldTime: '0.2.0',
    simulationControl: '0.3.0',
    simulationInterrupts: '0.1.0',
    timedTasks: '0.1.0',
    projects: '0.1.0',
    resourceProvenance: '0.1.0',
    resourceOpportunities: '0.1.0',
    resourceRecovery: '0.1.0',
    ecologyCatalog: '0.1.0',
    ecologyState: '0.1.0',
    populations: '0.1.0',
    gatheringSources: '0.1.0',
    resourceItems: '0.1.0',
    routeCatalog: '0.1.0',
    transport: '0.1.0',
    contentPackSchema: '0.1.0',
    regionalContentPacks: '0.1.0',
    contentPackValidation: '0.1.0',
    legacyCandidateNormalization: '0.1.0',
    simulationSubstrateGate: '0.1.0',
    dayCycle: '0.1.0',
    commandShell: '0.4.5',
    canvasUi: '0.7.0',
    uiIntents: '0.1.1',
    slashCommands: '0.4.1',
    accountSaves: '0.6.0',
    saveEncoding: '0.4.1',
    parser: '0.2.0',
    validation: '0.9.0',
    playerEntity: '0.7.0',
    characterCreation: '0.5.1',
    characterStats: '0.1.0',
    powers: '0.4.1',
    worldIdentity: '0.1.1',
    npcEntity: '0.2.0',
    enemyEntity: '0.2.1',
    statEngine: '0.5.0',
    statusEngine: '0.1.0',
    battleEngine: '0.5.0',
    combatActions: '0.5.1',
    battleRewards: '0.6.0',
    progression: '0.6.0',
    expTables: '0.5.2',
    disciplineSwitching: '0.6.0',
    skillProgression: '0.5.3',
    liveTick: '0.2.0',
    maps: '0.5.0',
    places: '0.5.0',
    coordinates: '0.1.0',
    navigation: '0.1.1',
    placeAtlas: '0.5.0',
    gridMovement: '0.4.0',
    hudControls: '0.4.0',
    aggro: '0.3.4',
    travel: '0.5.0',
    pois: '0.3.7',
    poiDiscovery: '0.3.6',
    poiFastTravel: '0.3.6',
    travelExits: '0.3.6',
    shops: '0.3.8',
    shopTransactions: '0.3.8',
    guilds: '0.3.5',
    questHooks: '0.3.5',
    inventoryContainers: '0.5.1',
    inventoryTransfers: '0.5.1',
    itemSchema: '0.7.0',
    itemBehavior: '0.1.0',
    itemStacking: '0.5.1',
    equipmentCommands: '0.5.0',
    equipmentEligibility: '0.5.1',
    itemInspection: '0.5.1',
    equipmentCatalog: '0.6.1',
    skillCaps: '0.5.2',
    homeStorage: '0.3.9',
    wardrobes: '0.3.9',
    achievements: 'planned',
    items: '0.7.0',
    keyItems: 'planned',
    magic: 'planned',
    loot: '0.5.1',
    leveling: '0.6.0',
    companions: 'planned',
    crafting: 'planned',
    mounts: 'planned',
});

export function describeVersion() {
    return [
        `Product: ${VERSION.product}`,
        `Package: ${VERSION.package}`,
        `Account Save: ${VERSION.accountSave}`,
        `Game State: ${VERSION.gameState}`,
        `Data: ${VERSION.data}`,
        `Benchmark: ${VERSION.benchmark}`,
        `Codename: ${VERSION.codename}`,
        `Compatibility: ${VERSION.compatibility}`,
    ].join('\n');
}

export function describeSystemVersions() {
    return Object.entries(SYSTEM_VERSIONS)
        .map(([system, version]) => `${system}: ${version}`)
        .join('\n');
}
