export const PRODUCT_VERSION = '0.8.500.1';
export const PACKAGE_VERSION = '0.8.500';

export const VERSION = Object.freeze({
    product: PRODUCT_VERSION,
    package: PACKAGE_VERSION,
    accountSave: 4,
    gameState: 5,
    data: 36,
    benchmark: 1,
    codename: 'Daily Social Availability',
    compatibility: 'pre-release-current-schema',
    released: false,
    app: PRODUCT_VERSION,
    save: 5,
});

export const SYSTEM_VERSIONS = Object.freeze({
    versionManifest: '0.8.500.1',
    saveMigrations: '0.3.0',
    actionResults: '0.1.0',
    semanticEvents: '0.1.0',
    foundationReadiness: '0.2.0',
    worldTime: '0.2.0',
    simulationControl: '0.3.0',
    simulationInterrupts: '0.1.0',
    timedTasks: '0.1.0',
    projects: '0.1.0',
    homeInfrastructure: '0.3.0',
    commitments: '0.3.0',
    relationships: '0.1.0',
    npcSchedules: '0.1.0',
    playerSocialSchedules: '0.1.0',
    resourceProvenance: '0.1.0',
    resourceOpportunities: '0.1.0',
    resourceRecovery: '0.1.0',
    resourceRecoveryWork: '0.3.0',
    characterActivity: '0.3.0',
    activityAdvance: '0.5.0',
    campaignRecovery: '0.1.0',
    workTasks: '0.1.0',
    workProficiencies: '0.1.0',
    workstations: '0.3.0',
    productionCatalog: '0.2.0',
    productionItems: '0.4.0',
    production: '0.1.0',
    settlementServiceBoard: '0.2.0',
    ecologyCatalog: '0.1.0',
    regionalEcology: '0.1.0',
    ecologyRegistry: '0.1.0',
    ecologyState: '0.1.0',
    populations: '0.2.0',
    gatheringSources: '0.3.0',
    gatheringWork: '0.1.0',
    resourceItems: '0.1.0',
    regionalResourceItems: '0.1.0',
    huntingResourceItems: '0.1.0',
    resourceItemRegistry: '0.2.0',
    routeCatalog: '0.1.0',
    transport: '0.3.0',
    carriedLoad: '0.2.0',
    transportServiceBoard: '0.2.0',
    contentPackSchema: '0.1.0',
    regionalContentPacks: '0.2.0',
    contentPackValidation: '0.1.0',
    legacyCandidateNormalization: '0.1.0',
    simulationSubstrateGate: '0.1.0',
    integratedMechanicsGate: '0.1.0',
    dayCycle: '0.2.0',
    commandShell: '0.5.0',
    domUi: '0.10.0',
    domOnboarding: '0.1.0',
    gameViewModels: '0.14.0',
    playerInformation: '0.1.1',
    playerExperience: '0.3.0',
    playerOpportunities: '0.2.0',
    playerContinuity: '0.5.0',
    playerCampaignReadability: '0.2.0',
    playerDangerRecovery: '0.2.0',
    localityNavigation: '0.2.0',
    canvasUi: '0.8.0',
    uiIntents: '0.10.0',
    slashCommands: '0.4.1',
    accountSaves: '0.6.0',
    saveRecovery: '0.1.0',
    saveEncoding: '0.4.1',
    parser: '0.2.0',
    validation: '0.10.0',
    playerEntity: '0.8.0',
    characterCreation: '0.6.0',
    characterCreationContent: '0.2.0',
    characterNames: '0.1.0',
    startingDisciplineKits: '0.1.0',
    characterStats: '0.1.0',
    capabilities: '0.2.0',
    abilityCatalog: '0.1.0',
    abilityEngine: '0.2.0',
    enemyAbilityCatalog: '0.1.0',
    companionCatalog: '0.2.0',
    party: '0.2.0',
    powers: '0.4.1',
    worldIdentity: '0.1.1',
    npcEntity: '0.2.0',
    enemyEntity: '0.4.0',
    statEngine: '0.5.0',
    statusEngine: '0.2.0',
    battleEngine: '0.8.0',
    combatTurns: '0.3.0',
    combatSimulation: '0.1.0',
    combatActions: '0.8.0',
    battleRewards: '0.6.0',
    progression: '0.6.0',
    expTables: '0.5.2',
    disciplineSwitching: '0.6.0',
    skillProgression: '0.6.0',
    liveTick: '0.2.0',
    maps: '0.5.0',
    places: '0.5.0',
    coordinates: '0.1.0',
    navigation: '0.1.1',
    placeAtlas: '0.5.0',
    gridMovement: '0.4.0',
    hudControls: '0.4.0',
    aggro: '0.3.4',
    travel: '0.5.0',
    pois: '0.3.7',
    poiDiscovery: '0.3.7',
    poiFastTravel: '0.3.6',
    travelExits: '0.3.6',
    shops: '0.4.0',
    shopTransactions: '0.5.0',
    guilds: '0.3.5',
    questHooks: '0.3.5',
    inventoryContainers: '0.6.0',
    inventoryTransfers: '0.6.0',
    itemSchema: '0.7.0',
    itemBehavior: '0.1.0',
    itemStacking: '0.5.1',
    equipmentCommands: '0.5.0',
    equipmentEligibility: '0.5.1',
    equipmentToolEngine: '0.1.0',
    itemInspection: '0.5.1',
    equipmentCatalog: '0.7.0',
    skillCaps: '0.5.2',
    homeStorage: '0.3.9',
    wardrobes: '0.3.9',
    achievements: 'planned',
    items: '0.7.0',
    keyItems: 'planned',
    magic: '0.1.0',
    abilities: '0.1.0',
    loot: '0.6.0',
    leveling: '0.6.0',
    companions: '0.2.0',
    crafting: '0.2.0',
    mounts: 'planned',
});

export function describeVersion() {
    return [
        `Product: ${VERSION.product}`,
        `Package: ${VERSION.package}`,
        `Account Save: ${VERSION.accountSave}`,
        `Game State: ${VERSION.gameState}`,
        `Data: ${VERSION.data}`,
        `Benchmark: ${VERSION.benchmark}`,
        `Codename: ${VERSION.codename}`,
        `Compatibility: ${VERSION.compatibility}`,
    ].join('\n');
}

export function describeSystemVersions() {
    return Object.entries(SYSTEM_VERSIONS)
        .map(([system, version]) => `${system}: ${version}`)
        .join('\n');
}
